name: 📗 Open an issue regarding the JinkoNo documentation
description: Let us know about any problematic API reference documents
labels: [doc]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for wanting to make JinkoNo better!

        Please fill in as much of the following form as you're able.
  - type: input
    attributes:
      label: Affected section
  - type: textarea
    attributes:
      label: Description of the problem
    validations:
      required: true
