blank_issues_enabled: true
contact_links:
  - name: Want to discuss something with the community?
    url: https://github.com/jinkono/community/discussions
    about: Please ask and answer questions here.
  - name: Want to request a feature or report a bug?
    url: https://github.com/jinkono/community/issues/new/choose
    about: Please file an issue here.
